更新rootfs

diff --git a/rootfs_cv1838/rootfs/etc/init.d/rcS b/rootfs_cv1838/rootfs/etc/init.d/rcS
--- a/rootfs_cv1838/rootfs/etc/init.d/rcS
+++ b/rootfs_cv1838/rootfs/etc/init.d/rcS
@@ -2,11 +2,95 @@
 echo /sbin/mdev > /proc/sys/kernel/hotplug
 /sbin/mdev -s && echo "mdev is ok......"
 
-export PATH=/usr/bin:/usr/sbin:/bin:/sbin:/root/firmware/app/bin:/root/firmware/app/scripts:/root/firmware/media/bin:/root/firmware/media/scripts:/root/firmware/app/3dr/bin:/root/platform
-export LD_LIBRARY_PATH=/lib:/usr/lib:/root/firmware/app/lib:/root/firmware/media/lib:/root/firmware/app/3dr/lib
-export EAPIL_APP_CONFIGS_DIR=/root/firmware/app/configs
-export EAPIL_MEDIA_CONFIGS_DIR=/root/firmware/media/configs
 # networking
 ifconfig lo 127.0.0.1 up
-/root/platform/init.sh
+
+source /etc/profile
+
+ubiattach /dev/ubi_ctrl -m 9
+if [ $? != 0  ]; then
+	ubiformat -y /dev/mtd9
+	ubiattach /dev/ubi_ctrl -m 9
+	ubimkvol /dev/ubi1 -N CFG -m
+fi
+
+if [ ! -c /dev/ubi1_0 ]; then
+	mdev -s
+fi
+mount -t ubifs -o sync /dev/ubi1_0 /root/configs
+if [ $? != 0  ]; then
+	echo 'Mount /root/configs failed, Try formatting and remounting'
+	ubimkvol /dev/ubi1 -N CFG -m
+	mount -t ubifs -o sync /dev/ubi1_0  /root/configs
+fi
+
+# select system
+cmdline=`cat /proc/cmdline`
+
+RunOnDoubleSystem(){
+    systemSelect=""
+    for item in $cmdline
+    do
+        result=$(echo $item | grep "systemSelect=")
+        if [[ "$result" != "" ]];then
+            if [[ "$result" == "systemSelect=A" ]];then
+                systemSelect="A"
+            elif [[ "$result" == "systemSelect=B" ]];then
+                systemSelect="B"
+            fi
+        fi
+    done
+    if [[ "$systemSelect" == "A" ]];then
+        mount -t squashfs /dev/mtdblock4 /root/firmware
+    elif [[ "$systemSelect" == "B" ]];then
+        mount -t squashfs /dev/mtdblock7 /root/firmware
+    else
+        echo "cannot found valid systemSelect"
+        exit
+    fi
+    echo "running on system $systemSelect"
+    export SPARE=0
+}
+
+RunOnSpareSystem(){
+    spare=""
+    for item in $cmdline
+    do
+        result=$(echo $item | grep "spare=")
+        if [[ "$result" != "" ]];then
+            if [[ "$result" == "spare=1" ]];then
+                spare="1"
+            elif [[ "$result" == "spare=0" ]];then
+                spare="0"
+            fi
+        fi
+    done
+    if [[ "$spare" == "0" ]];then
+        mount -t squashfs /dev/mtdblock4 /root/firmware
+    elif [[ "$spare" == "1" ]];then
+        mount -t squashfs /dev/mtdblock5 /root/firmware
+    else
+        echo "cannot found valid spare"
+        exit
+    fi
+    echo "running on spare = $spare"
+    export SPARE=$spare
+}
+
+find=0
+for item in $cmdline
+do
+    result=$(echo $item | grep "systemSelect=")
+    if [[ "$result" != "" ]];then
+       find=1
+       break
+    fi
+done
+if [[ "$find" == "1" ]];then
+    RunOnDoubleSystem
+else
+    RunOnSpareSystem
+fi
+
+appinit.sh
 
